name: Sofia Papadopoulou
url: https://sopa92.github.io/
designation: Programmer
baseurl: /
about_me: Hello visitor (^_^) It's me, your friendly Game Programmer in Red Kite Games Ltd! I come from Greece, but now 
  I live in Leeds, UK and this is my attempt to "connect" with you virtually! Well, in my current job I have been 
  programming in C++ daily (since I started in September 2020) and I am very proud for being part of the marvelous team 
  that ported "Control" to Stadia in 2021. 
  <br/><br/>
  In other news, I recently graduated with distinction from the MSc in 
  Computer Game Engineering of Newcastle University. I started this masters course following my passion for games 
  and at the same time, deciding that I will live and work abroad to achieve that. Moreover, in the first half of 2020, 
  I did a work placement as a Unity developer at Nosebleed Interactive Ltd, achieving to be in the credits of the 
  published mobile game 'The Pocket Arcade'. In addition, I look forward to seeing its PC version I have also worked on, 
  named 'Arcade Paradise', being released on Steam in the Spring of 2022. 
  <br/><br/>
  In Greece, I was a C# programmer for 3.5 years, 
  using ASP.NET, SQL, learning working with the Agile methodology, and in my free time, I had been developing my personal 
  small Unity projects. In total, I have almost 2 years of experience in game development and about 5 years in web development. 
  To sum up, programming is my everyday life, and at this point, I have to admit that the creative 
  and exciting world of the gaming industry has won me over!