name: Sofia Papadopoulou
url: https://sopa92.github.io/
designation: Programmer
baseurl: /
about_me: I am a game programmer in Red Kite Games Ltd. I've recently graduated with distinction from MSc in Computer Game Engineering at Newcastle University. I started this masters course following my passion for games. In 2020 I did a work placement as a Unity developer at Nosebleed Interactive Ltd. Programming is my everyday life. I have been a C# programmer for 3.5 years working on ASP.NET and SQL, using the Agile methodology. 
                    In total, I have 5 years of experience in web development and I am actively pursuing a career in the creative and exciting game industry.